#!/bin/bash

docker rm -fv supercontainer
docker build -t master-environment .
docker run  -d -v /var/tmp/rancher/:/var/tmp/rancher -v /var/tmp/rancher/supercontainer:/var/lib/docker --privileged --name=supercontainer master-environment
docker logs -f supercontainer
